### ISSUE TITLE
ImportError: cannot import name 'MyTinyImagenet' from 'tinyimagenet'

### ISSUE THREAD

**Issue by brillant222** [gydpku/GSA#1]
how to solve this problem? Do you have a good idea.

**Comment by gydpku** [comment]
Can you give me more details about the error?

**Comment by MyToumaKazusa** [comment]
Traceback (most recent call last):
  File "test_cifar100.py", line 26, in <module>
    import cifar as dataloader
  File "GSA/cifar.py", line 1509, in <module>
    from tinyimagenet import MyTinyImagenet
ModuleNotFoundError: No module named 'tinyimagenet'
